import { Inter } from "next/font/google";
import "./globals.css";
import Footers from "@/components/Footers";
import Nav from "@/components/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col justify-between h-screen">
          <div className="">
            <Nav />
            {children}
          </div>
          <div className="">
            <Footers />
          </div>
        </div>
      </body>
    </html>
  );
}
